version: '3.9'
# пример подключения к consul кластеру при помощи локально запущенного агента для java/python приложения
services:
  java-app:
    build:
      context: ./java-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=localhost
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul1
      - consul2
      - consul3

  python-app:
    build:
      context: ./python-app
    ports:
      - "8100:8100"
    environment:
      - CONSUL_HOST=localhost
      - CONSUL_PORT=8500
    depends_on:
      - consul1
      - consul2
      - consul3

  consul1:
    image: hashicorp/consul
    container_name: consul1
    command: agent -server -bootstrap-expect=3 -ui -client=0.0.0.0 -node=consul1 -retry-join=consul2 -retry-join=consul3
    ports:
      - "8500:8500"      # UI и HTTP API
      - "8600:8600/udp"  # DNS

  consul2:
    image: hashicorp/consul
    container_name: consul2
    command: agent -server -ui -client=0.0.0.0 -node=consul2 -retry-join=consul1 -retry-join=consul3
    ports:
      - "8502:8500"      # UI и HTTP API
      - "8602:8600/udp"  # DNS

  consul3:
    image: hashicorp/consul
    container_name: consul3
    command: agent -server -ui -client=0.0.0.0 -node=consul3 -retry-join=consul1 -retry-join=consul2
    ports:
      - "8503:8500"      # UI и HTTP API
      - "8603:8600/udp"  # DNS